### ISSUE TITLE
 Problem Responsive Design 

### ISSUE THREAD

**Issue by tushar-jadla** [eugenlee/NEC#4]
## Design Responsive 
I make the design for our home page. However, the design is not responsive yet.  But is that design is more comfortable with other pages as we applied to the same texture or same patterns.

**Comment by eugenlee** [comment]
Hi Tushar,

Looks good! Did you want to participate in Sprint 2? During Sprint 3 & 4, we will use Figma to redesign the website. Sprint 4 we will create the minimum viable product, which will be a one page website with a live messenger chat bot!

- Eugene
